module.exports = {
	ROOM_REALTIME: 'ROOM-001',
	SYSTEM_MAINTENANCE: 'SYS-001',
	SYSTEM_NEW_FEATURE: 'SYS-002',
	SHARE_QUIZ_TO_TEACHER: 'SHARE-001',
	SHARE_QUIZ_TO_CLASSROOM: 'SHARE-002',
	ADD_TO_ROOM: 'CLASSROOM-001',
	ADD_TO_CLASSROOM: 'CLASSROOM-002',
	STATUS_VERIFIED: 'SYS-003',
	// NOTIFY_SHARE_ROOM: 'ROOM-001',
};
